services:
  # content_api:
  #   build:
  #     context: ./src/api
  #     dockerfile: Dockerfile
  #   container_name: pinterest_content_api
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./content:/app/content:ro
  #   environment:
  #     CONTENT_DIR: /app/content

  app:
    image: nginx:alpine
    container_name: pinterest_app
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./src/app:/usr/share/nginx/html:ro

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql_server_dev
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
      MSSQL_PID: "Developer"

  mssql_init:
    image: mcr.microsoft.com/mssql-tools
    container_name: pinterest_mssql_init
    depends_on:
      - mssql
    volumes:
      - ./src/scripts:/scripts:ro
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
    command: ["bash", "/scripts/init_db.sh"]
    restart: 'no'

  dotnet_api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: pinterest_dotnet_api
    restart: unless-stopped
    ports:
      - "8083:5000"
    volumes:
      - ./src/dotnet_api:/app:rw
    working_dir: /app
    environment:
      DOTNET_ENVIRONMENT: Development
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:5000"]
    # depends_on:
    #   - mssql_init

volumes:
  mssql_data:
